// src/components/Editor.tsx
import styles from '~/styles/App.module.css';
import type { Component } from 'solid-js';

import { createSignal, onMount } from "solid-js";
import * as monaco from "monaco-editor"

import { fs } from "@tauri-apps/api";
import { invoke } from "@tauri-apps/api";


interface inProps{
    path: string,
    renderer: Function
}


async function initEditor(div: HTMLDivElement, path: string | undefined, renderer: Function) {
    let [texte, setTexte] = createSignal("= caca \n $1/2$")

    if (path) {
        let buff = (await fs.readBinaryFile(path))
        let buff2 = buff as unknown as number[]
        setTexte(String.fromCharCode.apply(null, buff2))
    }

    let editor = monaco.editor.create(div, {
        theme: "vs-dark",
        minimap: {
            enabled: false
        },
        automaticLayout: true,
        value: texte()
    })

    editor.onDidChangeModelContent((event) => {
        setTexte(editor.getValue())
        invoke("update_project", { content: texte() }).then()
        renderer()
    })

}


export default (props:inProps) => {
    const [path] = createSignal();

    let div: HTMLDivElement = document.createElement("div")
    div.style.height = "100%"
    initEditor(div, props.path, props.renderer)

    return (
        div
    )
}

// src/lib/components/editor.svelte
<script lang="ts">
  import * as monaco from "monaco-editor";

  import { fs, invoke } from "@tauri-apps/api";
  import { onMount } from "svelte";

  let {
    path,
    uri = $bindable(),
  }: {
    path: string;
    uri: string;
  } = $props();

  let texte = $state("= demo \n $1/2$");

  async function initEditor(div: HTMLDivElement, path: string | undefined) {
    if (path) {
      let buff = await fs.readBinaryFile(path);
      let buff2 = buff as unknown as number[];
      texte = String.fromCharCode.apply(null, buff2);
    }

    let editor = monaco.editor.create(div, {
      theme: "vs-dark",
      minimap: {
        enabled: false,
      },
      automaticLayout: true,
      value: texte,
    });

    editor.onDidChangeModelContent(async (event) => {
      texte = editor.getValue();
      invoke("update_project", { content: texte }).then();
      invoke("compile_project").then();
      let data = await invoke("render_project", { page: 0 });
      uri = `data:image/svg+xml;utf8,${encodeURIComponent(data)}`;
    });
  }

  let div: HTMLDivElement;
  onMount(() => {
    initEditor(div, path);
  });
</script>

<div class="h-dvh" bind:this={div}></div>
